### ISSUE TITLE
TODO 清单

### ISSUE THREAD

**Issue by LonelySteve** [LonelySteve/Drawing#1]
# 调整工作
## 1. 构造函数

- [x] 调整每个图元类构造函数的参数顺序，视使用率从高到低排序
- [x] 调整 CShape 类中默认成员变量值，具体以纯黑填充和无边框为准

## 2. 图元类绘制

- [x] 在 CShape 类中定义 ToDraw 函数，接受一个CDC指针参数。Draw 函数内部维护钢笔和刷子的选取和归还，并在选择好钢笔和刷子后调用ToDraw函数，将 pDC 传入。调用完成后归还旧钢笔和笔刷。子类重写ToDraw函数，其中就可只写关键的绘制代码

**Comment by LonelySteve** [comment]
# 基础建设工作
## 1. 显示图形

- [x] 完成每个非抽象图元类的 ToDraw 函数定义

## 2. 存储图形

- [x] 完成每个非抽象图元类的序列化工作

## 3. 选中图形

- [x]  完成每个非抽象图元类的 IsMatch 函数定义

**Comment by LonelySteve** [comment]
# 后期建设工作
## 1. 删除图形

- [x] 实现左键双击事件处理程序，以删除对应的图元对象

## 2. 图形属性对话框

- [x] 建立任务书上描述一致的对话框
- [x] 按照需求设置或生产图元对象

## 3. 新建图形与修改图形

- [x] 弹出图形属性对话框以完成相应需求
